security:
    encoders:
        App\Entity\Admin\User:
            algorithm: auto
    providers:
        admin:
            id: App\Admin\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: true
            lazy: true
            pattern: ^/
            host: '%app.admin_host%'
            provider: admin
            guard:
                authenticators:
                    - App\Admin\Security\LoginFormAuthenticator
            logout:
                path: admin_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/login, host: '%app.admin_host%', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, host: '%app.admin_host%', roles: ROLE_USER }

