image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

services:
    - name: mysql:latest
      command: ['--sql_mode=""']

variables:
    MYSQL_DATABASE: database
    MYSQL_USER: runner
    MYSQL_ROOT_PASSWORD: password
    MYSQL_PASSWORD: password

cache:
    paths:
        - ./vendor/
        - ./node_modules/

before_script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress

stages:
    - lint
    - test

lint:
    stage: lint
    script:
        - composer lint

test:
    stage: test
    before_script:
        - sudo chmod +x ./bin/console
        - sudo chmod +x ./bin/phpunit
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress
        - yarn install
        - yarn build
        - bin/console doctrine:database:drop --force --env=test
        - bin/console doctrine:database:create --env=test
        - bin/console doctrine:schema:create --env=test
        - bin/phpunit
    script:
        - bin/phpunit --coverage-text --colors=never tests