image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

services:
    - mysql:latest

variables:
    MYSQL_DATABASE: database
    MYSQL_USER: runner
    MYSQL_ROOT_PASSWORD: password
    MYSQL_PASSWORD: password

cache:
    paths:
        - ./vendor/

before_script:
    - sudo chmod +x ./bin/console
    - sudo chmod +x ./bin/phpunit
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - bin/console doctrine:database:drop --force --env=test
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:create --env=test
    - bin/console doctrine:fixtures:load -n --env=test
    - bin/phpunit

stages:
    - lint
    - test

lint:
    stage: lint
    script:
        - composer lint

test:
    stage: test
    script:
        - bin/phpunit --coverage-text --colors=never tests