parameters:
    app.admin_host: '%env(APP_ADMIN_HOST)%'
    app.webshop_host: '%env(APP_WEBSHOP_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Admin\Controller\:
        resource: '../src/Admin/Controller/'
        tags: ['controller.service_arguments']

    App\Timestampable\TimestampableSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
