parameters:
    app.admin_host: '%env(APP_ADMIN_HOST)%'
    app.webshop_host: '%env(APP_WEBSHOP_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Menu\MenuTypeInterface:
            tags: ['app.menu_type']

    App\:
        resource: '../src/{Admin,DataFixtures,Repository,Twig}'

    App\ActionLog\ActionLogger: ~

    App\ActionLog\ActionLogSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\ActionLog\Report\ActionLogReportFactory: ~

    App\Admin\Controller\:
        resource: '../src/Admin/Controller/'
        tags: ['controller.service_arguments']

    App\Menu\MenuFactory:
        public: true
        arguments:
            $types: !tagged { tag: 'app.menu_type', index_by: true, default_index_method: 'getKey' }

    App\Timestampable\TimestampableSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }
